{% set name = "openspoor" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openspoor-{{ version }}.tar.gz
  sha256: 148f0c16976f749c3079bc23bbbe2a73a8e384e0e97e8b53faf9af1eaaef9709

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - folium
    - geopandas
    - importlib-metadata
    - loguru
    - pandas
    - pyproj <3
    - python >=3.7
    - pyyaml
    - requests
    - rtree
    - shapely

test:
  imports:
    - openspoor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/openspoor/
  summary: Open source project to allow translations between different spoor referential systems
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ProRail-DataLab
